### ISSUE TITLE
No shortcut, keystroke, to open vBookmarks (right?)

### ISSUE THREAD

**Issue by WaterSibilantFalling** [windviki/vBookmarks#10]
As far as I can see, there is no shortcut keystroke to open vBookmarks. 

Having no keyboard shortcut removes the reason for an 'add bookmark here' type plugin: because you then have to use your mouse. If we are going to have to use our mouse then we might as well use the clumbsy built-in process. 

vBookmarks really needs a keyboard shortcut.

**Comment by windviki** [comment]
You can use Ctrl+Shift+B to open vBookmarks popup.
But yes, there's no shortcut for context menu items by now.

**Comment by WaterSibilantFalling** [comment]
Can use Shift + F10 to open the focus' location's context menu, which does for me. 
Also can do

        xmodmap -e "keycode  107 = Menu"

to map a key (keycode 107) to the context menu. 

Closing this.
