### ISSUE TITLE
嘤嘤嘤...能增加自定义宽度高度以及自定义图标吗?

### ISSUE THREAD

**Issue by Noah1995** [windviki/vBookmarks#11]
1丶能增加自定义宽度丶高度以及自定义图标吗?

2丶能否小数字显示所有书签数量...
自定义文件夹里面的书签数量切换...

**Comment by Noah1995** [comment]
3丶还有就是添加书签的时候能否让它根据添加时间最新的在前面...

4丶还有永远批量置顶书签...看下效果图差不多这个意思...

![【Snipaste】【2019-07-18】No 204037](https://user-images.githubusercontent.com/25548230/61458099-5eae8a00-a99c-11e9-9034-4bc0b6ede1c3.jpg)

**Comment by windviki** [comment]
> 1丶能增加自定义宽度丶高度以及自定义图标吗?
> 
> 2丶能否小数字显示所有书签数量...
> 自定义文件夹里面的书签数量切换...

1. 都可以通过高级选项里的CSS进行自定义。图标自定义在高级选项里直接就有。

2. 暂时没精力搞新功能 :)

包括后面的两个需求，都还挺不错。和目前的菜单有些冲突，要做好的话需要时间。暂时open作为以后的计划功能吧

**Comment by windviki** [comment]
补充：
Chrome extension popups have a maximum height of 600px and maximum width of 800px.
所以目前是高度不可自定义（默认的是尽可能达到了600像素高度）
宽度一直就是允许拖动的。

**Comment by Noah1995** [comment]
我现在才发现有高级选项和拖动...

还有大佬有兴趣研发一下类似遨游的自定义多重搜索引擎吗?
![【2018 12 26】【14∶50∶45】](https://user-images.githubusercontent.com/25548230/63563065-6dd3b980-c592-11e9-96fa-35d1049140de.gif)
我这边用了N个拓展各有不同的好...
想找人把我的想法做个融合...

**Comment by windviki** [comment]
Off topic. Closed.
