### ISSUE TITLE
[Feature Request] search for folders in bookmark search bar

### ISSUE THREAD

**Issue by GorvGoyl** [windviki/vBookmarks#15]
currently search bar shows only bookmarks, it would be convenient if you can also search for folders along with bookmarks.

**Comment by windviki** [comment]
This makes sense. Will be implemented in versions after v3.1.

**Comment by GorvGoyl** [comment]
Hey @windviki , just a reminder.. could really use this feature.

**Comment by windviki** [comment]
It has been implemented in my branch, and currently it's under testing. Be patience. It's coming :)
