### ISSUE TITLE
Terrible incremental search when searching

### ISSUE THREAD

**Issue by WaterSibilantFalling** [windviki/vBookmarks#24]
"Terrible" is the mildest word I can use. 

So, if anyone searches their bookmarks for "share":
1.  All the bookmarks including "s" are found and then shown: insanity
2. Next the bookmarks including "sh" are found and then shown: insanity
3. Next the bookmarks including "sha" are found and then shown: insanity
4. Next the bookmarks including "shar" are found and then shown: insanity
5. Next the bookmarks including "share" are found and then shown. At last, 15 seconds later. 

This is Terrible design. Why oh why? 

But wait, there's more:

If I type "*" in the omnibar, and then type "share", my browser freezes (yay!) for 15 seconds. 

What should happen: when <cr> is read, then a SINGLE search is done for the single search string.  Ah, sanity.

**Comment by windviki** [comment]
This is the original design from Neat Bookmarks.
It's not so "terrible" for those who have thousands of bookmarks and search on a modern device. I cannot even notice the latency.
But I think maybe you're right, in some cases this will cause bad search performance. So I'll provide an option to disable the "instant search". You can upgrade to the coming v3.3, and then you can search with ENTER pressed.
