### ISSUE TITLE
Automatically closing

### ISSUE THREAD

**Issue by YesTrustMe** [windviki/vBookmarks#32]
When (trying) to edit and organize your bookmarks, most everyone will need to open the lihk first. However, with this extension, it automatically closes and you're forced to open up the extension again. 

Fortunately, the placemark is remembered, but there should be an option to have the bar open in advanced settings. Otherwise, it's very time consuming to organize bookmarks when you have to open the extension each time after you view the opened bookmark.

**Comment by windviki** [comment]
You can try the 4th checkbox in the extension settings page.
