### ISSUE TITLE
书签图标还有文字在MacBook Pro 的 Retina 显示屏上不适配~

### ISSUE THREAD

**Issue by superleeyom** [windviki/vBookmarks#8]
我的电脑是retina屏幕的mac电脑, 使用该插件, 书签图标和文字感觉看上去有点模糊的感觉, 应该是没有适配高分屏吧? 如果可以的话, 希望能修复下~谢谢

**Comment by windviki** [comment]
Not sure what to do about high-resolution support of Chrome extensions. Reopen it if there's some new information.
